server:
  port: 8001

spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource             # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.92.128:3306/springcloudDemo?rewriteBatchedStatements=true&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: hct

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.hct.springcloud.pojos    # 所有Pojo别名类所在包